# title: consolo

author:
#  name: Jay Doe
  email: justin@bustinbung.com
  github_username: bustinbung

header_pages:
  - index.md
  - about.md
  - projects.md
  - blog.md
footer_message: '&lt;/&gt; with &lt;3, 2023'
style: dark
date-format: "%Y-%m-%d"
permalink: /:categories/:title

# google_analytics: G-NNNNNNNNNN
goatcounter_analytics: bustinbung

sass:
  style: :compressed